name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - refactoring
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (test or prod)'
        required: true
        default: 'test'
        type: string

env:
  BRANCH_NAME: ${{ github.ref_name }}
  COMMIT_HASH: ${{ github.sha }}
  BUCKET_NAME: abacus-internal-glue-artefacts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

      - name: Run tests
        run: poetry run pytest tests/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build package
        run: poetry build

      - name: Upload package to S3
        run: |
          DATE=$(date -u +'%Y%m%d')
          aws s3 cp dist/*.whl s3://${{ env.BUCKET_NAME }}/${{ env.BRANCH_NAME }}/$DATE/${{ env.COMMIT_HASH }}/abacus.whl
          aws s3 cp dist/*.whl s3://${{ env.BUCKET_NAME }}/${{ env.BRANCH_NAME }}/latest/abacus.whl
          aws s3 cp main.py s3://${{ env.BUCKET_NAME }}/${{ env.BRANCH_NAME }}/$DATE/${{ env.COMMIT_HASH }}/main.py
          aws s3 cp main.py s3://${{ env.BUCKET_NAME }}/${{ env.BRANCH_NAME }}/latest/main.py
